name: Deploy E-Shop on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: SSH into the instance and run Ansible playbook
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ec2-user@${{ secrets.HOST }} << EOF
          echo "${{ secrets.VAULT_PASS }}" > vault_pass.txt
          ansible-playbook /4IT572_ansible/ansible/ec2_deploy.yml --vault-password-file vault_pass.txt --key-file /4IT572_ansible/ansible/devopss.pem
          rm -f vault_pass.txt
          EOF
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          ANSIBLE_HOST_KEY_CHECKING: False
