name: Deploy EShop on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode SSH Key
      run: |
        echo "${{ secrets.SSH_KEY }}" | base64 --decode > ssh_key
        chmod 600 ssh_key

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Run Ansible Playbook
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        ANSIBLE_HOST_KEY_CHECKING: False
      run: |
        ansible-playbook 4IT572_ansible/ansible/ec2_deploy.yml -e ansible_ssh_private_key_file=ssh_key --user ec2-user
