name: SSH Connectivity Testt

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH Key File
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ./ssh_key
          script: |
            echo "Testing SSH connection"
