name: SSH Connectivity Test 

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" | base64 --decode > ssh_key
          chmod 600 ssh_key

      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Testing SSH connection"
